spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order-management
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: order-manager
  mail:
    host: smtp.gmail.com
    port: 587
    username: removed@gmail.com
    password: removed
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: WARN
    com.sibs: DEBUG
